# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SD_System/SD_System.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD_System || ORIG_REF_NAME==SD_System} -quiet] -quiet

# IP: bd/SD_System/ip/SD_System_processing_system7_0_0/SD_System_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD_System_processing_system7_0_0 || ORIG_REF_NAME==SD_System_processing_system7_0_0} -quiet] -quiet

# IP: bd/SD_System/ip/SD_System_axi_gpio_0_0/SD_System_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD_System_axi_gpio_0_0 || ORIG_REF_NAME==SD_System_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SD_System/ip/SD_System_axi_smc_0/SD_System_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD_System_axi_smc_0 || ORIG_REF_NAME==SD_System_axi_smc_0} -quiet] -quiet

# IP: bd/SD_System/ip/SD_System_rst_ps7_0_100M_0/SD_System_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD_System_rst_ps7_0_100M_0 || ORIG_REF_NAME==SD_System_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/SD_System_ooc.xdc
