
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_INTERCONNECT_GPIO_DEVICE_ID,
		XPAR_INTERCONNECT_GPIO_BASEADDR,
		XPAR_INTERCONNECT_GPIO_INTERRUPT_PRESENT,
		XPAR_INTERCONNECT_GPIO_IS_DUAL
	},
	{
		XPAR_SPEED_GPIO_DEVICE_ID,
		XPAR_SPEED_GPIO_BASEADDR,
		XPAR_SPEED_GPIO_INTERRUPT_PRESENT,
		XPAR_SPEED_GPIO_IS_DUAL
	},
	{
		XPAR_X_GPIO_DEVICE_ID,
		XPAR_X_GPIO_BASEADDR,
		XPAR_X_GPIO_INTERRUPT_PRESENT,
		XPAR_X_GPIO_IS_DUAL
	},
	{
		XPAR_Y_GPIO_DEVICE_ID,
		XPAR_Y_GPIO_BASEADDR,
		XPAR_Y_GPIO_INTERRUPT_PRESENT,
		XPAR_Y_GPIO_IS_DUAL
	},
	{
		XPAR_Z_GPIO_DEVICE_ID,
		XPAR_Z_GPIO_BASEADDR,
		XPAR_Z_GPIO_INTERRUPT_PRESENT,
		XPAR_Z_GPIO_IS_DUAL
	}
};


