# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.srcs/sources_1/bd/SD_System/ip/SD_System_axi_gpio_0_2/SD_System_axi_gpio_0_2.xci
# IP: The module: 'SD_System_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_gpio_0_2/SD_System_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_gpio_0_2/SD_System_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_gpio_0_2/SD_System_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.srcs/sources_1/bd/SD_System/ip/SD_System_axi_gpio_0_2/SD_System_axi_gpio_0_2.xci
# IP: The module: 'SD_System_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_gpio_0_2/SD_System_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_gpio_0_2/SD_System_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_gpio_0_2/SD_System_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
