# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: X:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.srcs/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/SD_System_axi_smc_0.xci
# IP: The module: 'SD_System_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/bd_d332.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_0/bd_d332_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_1/bd_d332_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_2/bd_d332_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_3/bd_d332_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_4/bd_d332_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_5/bd_d332_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_6/bd_d332_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_7/bd_d332_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_8/bd_d332_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_9/bd_d332_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_10/bd_d332_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_11/bd_d332_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_12/bd_d332_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_13/bd_d332_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_14/bd_d332_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_15/bd_d332_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_16/bd_d332_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_17/bd_d332_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_18/bd_d332_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_19/bd_d332_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_20/bd_d332_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_21/bd_d332_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_22/bd_d332_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_23/bd_d332_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_24/bd_d332_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_25/bd_d332_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_26/bd_d332_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_27/bd_d332_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_28/bd_d332_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_29/bd_d332_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_30/bd_d332_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_31/bd_d332_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_32/bd_d332_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_33/bd_d332_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_34/bd_d332_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_35/bd_d332_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_36/bd_d332_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_37/bd_d332_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_38/bd_d332_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_39/bd_d332_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_40/bd_d332_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_41/bd_d332_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_42/bd_d332_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_43/bd_d332_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_44/bd_d332_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_45/bd_d332_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_46/bd_d332_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_47/bd_d332_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_48/bd_d332_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_49/bd_d332_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_50/bd_d332_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_51/bd_d332_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_52/bd_d332_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_53/bd_d332_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_54/bd_d332_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_55/bd_d332_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_56/bd_d332_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_57/bd_d332_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_58/bd_d332_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_59/bd_d332_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_60/bd_d332_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_1/bd_d332_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_1/bd_d332_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_2/bd_d332_arinsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_3/bd_d332_rinsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_4/bd_d332_awinsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_5/bd_d332_winsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_6/bd_d332_binsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_7/bd_d332_aroutsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_8/bd_d332_routsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_9/bd_d332_awoutsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_10/bd_d332_woutsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_11/bd_d332_boutsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_12/bd_d332_arni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_13/bd_d332_rni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_14/bd_d332_awni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_15/bd_d332_wni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_16/bd_d332_bni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_20/bd_d332_s00a2s_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_21/bd_d332_sarn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_22/bd_d332_srn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_23/bd_d332_sawn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_24/bd_d332_swn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_25/bd_d332_sbn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_26/bd_d332_m00s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_27/bd_d332_m00arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_28/bd_d332_m00rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_29/bd_d332_m00awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_30/bd_d332_m00wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_31/bd_d332_m00bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_33/bd_d332_m01s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_34/bd_d332_m01arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_35/bd_d332_m01rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_36/bd_d332_m01awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_37/bd_d332_m01wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_38/bd_d332_m01bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_40/bd_d332_m02s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_41/bd_d332_m02arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_42/bd_d332_m02rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_43/bd_d332_m02awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_44/bd_d332_m02wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_45/bd_d332_m02bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_47/bd_d332_m03s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_48/bd_d332_m03arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_49/bd_d332_m03rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_50/bd_d332_m03awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_51/bd_d332_m03wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_52/bd_d332_m03bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_54/bd_d332_m04s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_55/bd_d332_m04arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_56/bd_d332_m04rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_57/bd_d332_m04awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_58/bd_d332_m04wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_59/bd_d332_m04bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: X:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.srcs/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/SD_System_axi_smc_0.xci
# IP: The module: 'SD_System_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/bd_d332.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_0/bd_d332_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_1/bd_d332_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_2/bd_d332_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_3/bd_d332_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_4/bd_d332_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_5/bd_d332_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_6/bd_d332_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_7/bd_d332_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_8/bd_d332_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_9/bd_d332_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_10/bd_d332_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_11/bd_d332_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_12/bd_d332_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_13/bd_d332_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_14/bd_d332_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_15/bd_d332_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_16/bd_d332_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_17/bd_d332_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_18/bd_d332_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_19/bd_d332_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_20/bd_d332_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_21/bd_d332_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_22/bd_d332_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_23/bd_d332_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_24/bd_d332_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_25/bd_d332_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_26/bd_d332_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_27/bd_d332_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_28/bd_d332_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_29/bd_d332_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_30/bd_d332_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_31/bd_d332_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_32/bd_d332_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_33/bd_d332_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_34/bd_d332_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_35/bd_d332_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_36/bd_d332_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_37/bd_d332_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_38/bd_d332_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_39/bd_d332_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_40/bd_d332_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_41/bd_d332_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_42/bd_d332_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_43/bd_d332_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_44/bd_d332_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_45/bd_d332_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_46/bd_d332_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_47/bd_d332_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_48/bd_d332_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_49/bd_d332_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_50/bd_d332_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_51/bd_d332_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_52/bd_d332_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_53/bd_d332_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_54/bd_d332_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_55/bd_d332_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_56/bd_d332_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_57/bd_d332_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_58/bd_d332_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_59/bd_d332_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_60/bd_d332_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_1/bd_d332_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_1/bd_d332_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_2/bd_d332_arinsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_3/bd_d332_rinsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_4/bd_d332_awinsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_5/bd_d332_winsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_6/bd_d332_binsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_7/bd_d332_aroutsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_8/bd_d332_routsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_9/bd_d332_awoutsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_10/bd_d332_woutsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_11/bd_d332_boutsw_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_12/bd_d332_arni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_13/bd_d332_rni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_14/bd_d332_awni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_15/bd_d332_wni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_16/bd_d332_bni_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_20/bd_d332_s00a2s_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_21/bd_d332_sarn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_22/bd_d332_srn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_23/bd_d332_sawn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_24/bd_d332_swn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_25/bd_d332_sbn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_26/bd_d332_m00s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_27/bd_d332_m00arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_28/bd_d332_m00rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_29/bd_d332_m00awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_30/bd_d332_m00wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_31/bd_d332_m00bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_33/bd_d332_m01s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_34/bd_d332_m01arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_35/bd_d332_m01rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_36/bd_d332_m01awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_37/bd_d332_m01wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_38/bd_d332_m01bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_40/bd_d332_m02s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_41/bd_d332_m02arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_42/bd_d332_m02rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_43/bd_d332_m02awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_44/bd_d332_m02wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_45/bd_d332_m02bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_47/bd_d332_m03s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_48/bd_d332_m03arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_49/bd_d332_m03rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_50/bd_d332_m03awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_51/bd_d332_m03wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_52/bd_d332_m03bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_54/bd_d332_m04s2a_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_55/bd_d332_m04arn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_56/bd_d332_m04rn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_57/bd_d332_m04awn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_58/bd_d332_m04wn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/bd_0/ip/ip_59/bd_d332_m04bn_0_ooc.xdc

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: x:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
