# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.srcs/sources_1/bd/SD_System/ip/SD_System_processing_system7_0_0/SD_System_processing_system7_0_0.xci
# IP: The module: 'SD_System_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_processing_system7_0_0/SD_System_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.srcs/sources_1/bd/SD_System/ip/SD_System_processing_system7_0_0/SD_System_processing_system7_0_0.xci
# IP: The module: 'SD_System_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Git-Repos/CNC-FPGA/SD_Demo/SD_Demo.gen/sources_1/bd/SD_System/ip/SD_System_processing_system7_0_0/SD_System_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD_System_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
